server:
  port: 8082

spring:
  application:
    name: stock-service
  datasource:
      url: jdbc:mysql://192.168.3.2:3306/shopping_mall_db
      username: pawan
      password: pawan
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update