server:
  port: 8082

spring:
  application:
    name: stock-service
  datasource:
      url: jdbc:mysql://10.0.0.79:3306/shopping_mall_db
      username: sanketh
      password: sanketh
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update